data:
  raw_data_path: "data/raw/Dataset.csv"
  data_dict_path: "data/raw/Data_Dictionary.csv"
  processed_data_path: "data/processed/"
  
model:
  target_column: "Default"
  test_size: 0.2
  random_state: 42
  models:
    xgboost:
      max_depth: 6
      learning_rate: 0.1
      n_estimators: 200
      subsample: 0.8
      scale_pos_weight: 11.38
      
evaluation:
  cv_folds: 5
  scoring: ['roc_auc', 'precision', 'recall', 'f1']
  
mlflow:
  experiment_name: "loan_default_prediction"
  tracking_uri: "file:./mlruns"data:
  raw_data_path: "data/raw/Dataset.csv"
  data_dict_path: "data/raw/Data_Dictionary.csv"
  processed_data_path: "data/processed/"
  
model:
  target_column: "Default"
  test_size: 0.2
  random_state: 42
  models:
    xgboost:
      max_depth: 6
      learning_rate: 0.1
      n_estimators: 200
      subsample: 0.8
      scale_pos_weight: 11.38
      
evaluation:
  cv_folds: 5
  scoring: ['roc_auc', 'precision', 'recall', 'f1']
  
mlflow:
  experiment_name: "loan_default_prediction"
  tracking_uri: "file:./mlruns"